# Generated by Django 5.0.6 on 2024-07-08 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=64)),
                ('Name', models.CharField(max_length=64)),
                ('FatherName', models.CharField(max_length=64)),
                ('Email', models.EmailField(max_length=64)),
                ('Country', models.CharField(max_length=64)),
                ('City', models.CharField(max_length=64)),
                ('DateOfBirth', models.DateField()),
                ('PhoneNumber', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CyberSport',
            fields=[
                ('single_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.single')),
                ('Game', models.CharField(max_length=64)),
                ('ParticipateFormat', models.CharField(max_length=64)),
            ],
            bases=('register.single',),
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('single_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.single')),
                ('course', models.CharField(max_length=64)),
            ],
            bases=('register.single',),
        ),
        migrations.CreateModel(
            name='DroneRace',
            fields=[
                ('single_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.single')),
            ],
            bases=('register.single',),
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('single_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.single')),
                ('course', models.CharField(max_length=64)),
            ],
            bases=('register.single',),
        ),
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('single_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.single')),
                ('speech_theme', models.CharField(max_length=255)),
            ],
            bases=('register.single',),
        ),
        migrations.CreateModel(
            name='Mobilography',
            fields=[
                ('single_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.single')),
            ],
            bases=('register.single',),
        ),
        migrations.CreateModel(
            name='Robotix',
            fields=[
                ('single_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.single')),
            ],
            bases=('register.single',),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('single_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.single')),
                ('speech_theme', models.CharField(max_length=255)),
            ],
            bases=('register.single',),
        ),
    ]
