# Generated by Django 5.0.6 on 2024-06-12 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0003_remove_sections_icon_remove_sections_mapp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.IntegerField()),
                ('chek', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chek', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('surname', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('phone', models.CharField(max_length=225)),
                ('age', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=225)),
                ('confirmation_code', models.IntegerField(editable=False)),
                ('accepted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.sections')),
            ],
        ),
    ]
