# Generated by Django 5.0.7 on 2024-07-10 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_name', models.CharField(max_length=100)),
                ('Legal_name', models.CharField(max_length=100)),
                ('Legal_address', models.CharField(max_length=100)),
                ('INN', models.IntegerField()),
                ('Supervisor_Name', models.CharField(max_length=100)),
                ('Job_Title', models.CharField(max_length=100)),
                ('Company_Activity', models.CharField(max_length=255)),
                ('Web_Site', models.URLField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Theme', models.CharField(max_length=100)),
                ('Company_Product', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Expo',
            fields=[
                ('foodzone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company_register.foodzone')),
            ],
            bases=('company_register.foodzone',),
        ),
    ]
