# Generated by Django 5.0.7 on 2024-07-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodzone',
            name='Theme',
        ),
        migrations.AddField(
            model_name='foodzone',
            name='Logo',
            field=models.ImageField(default=1, upload_to='logos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodzone',
            name='register_check',
            field=models.ImageField(default=1, upload_to='register_check/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='it_expo',
            name='Theme',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
