# Generated by Django 5.0.7 on 2024-07-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_register', '0002_remove_foodzone_theme_foodzone_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodzone',
            old_name='register_check',
            new_name='Register_check',
        ),
        migrations.AddField(
            model_name='foodzone',
            name='Phone_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
